### PR TITLE
Fix akward horizontal scroll on mobile

### PR DESCRIPTION
**Pull request by TheBushyBrow**
Tested on desktop and mobile widths

### CODE REVIEW

**Comment by wopian** [comment]
Hiding horizontal overflow hides the problem instead of fixing it&mdash;there is still an element causing the viewport to be too wide

**Review by wopian — CHANGES_REQUESTED** [review]
Hiding horizontal overflow simply hides the problem instead of fixing it&mdash;there is still an element causing the viewport to be too wide.

I also suggest moving it to [shame.scss](https://github.com/TheBushyBrow/hummingbird-client/blob/the-future/app/styles/base/_shame.scss) as a temporary hack

**Comment by TheBushyBrow** [comment]
Good call @wopian, I just moved it to _Shame for now until I have time to investigate which elements are actually expanding outside its containers.  Thanks~

**Comment by JoshFabian** [comment]
Yeah, shame is a good place for this for the time being! Thanks for the PR!

**Comment by wopian** [comment]
The cause of the overflow is possibly the search bar - it also causes the right navbar content to reflow onto a second line when expanded.

**Comment by cybrox** [comment]
@wopian The cause of the overflow on pages with feed, is related to the footer of the feed entries. I tracked and fixed some more a while ago (especially related to right-aligned drop-downs) but I didn't really figure this one out.
I think squash-merging this works for now, since it hides the problem until we get around to properly fix it.

**Comment by TheBushyBrow** [comment]
@wopian and @cybrox I'll add your notes to the story on pivotal so we have a place to start next time we pick this up.

**Pull request merged**
