### PR TITLE
Post hide actions

### PR DESCRIPTION
**Pull request by matthewdias**
todo:
- [x] post hide actions on group page and group list
- [x] make group-list actions clickable
- [x] group posts hide action on group posts
- [x] actions on user profile, user lists, post
    - [x] blocking
    - [x] hiding posts
- [x] media unfollows
    - [x] post action
    - [x] media page action

### CODE REVIEW

**Comment by matthewdias** [comment]
getting `Internal Server Error: undefined method 'user_id' for #<Class:0x00559d8b5b5210> /usr/local/bundle/gems/activerecord-4.2.8/lib/active_record/dynamic_matchers.rb:26:in 'method_missing'` for `group_member` inside the `is_owner?` method @NuckChorris

**Comment by matthewdias** [comment]
@vevix im having issues getting the dropdown to show in `groups-list` cuz its wrapped in an anchor with an action.

**Comment by trmcnvn** [comment]
@matthewdias Check out my latest usage of dropdowns using ember-basic-dropdown over the bootstrap approach. (rating-button, status-dropdown, etc.). Might have more luck.

**Comment by matthewdias** [comment]
Blockers: 
- `undefined method 'arel_table' for Media:Module` @NuckChorris 
- design location for 3 dot menu @JoshFabian

**Review by trmcnvn — CHANGES_REQUESTED** [review]
It's not worth using tasks if we aren't going to take advantage of their features (`isRunning`, etc.) -- Most of these ajax requests could just be actions or functions, which would result in a lot less code as well after it is transpiled.

-----

`media-follow` component should be deleted here with these changes.

-----

Mocking the `/follows` API in Mirage should fix the tests.

**Review by trmcnvn — APPROVED** [review]

**Pull request merged**
