### PR TITLE
Fix layout of episode images

### PR DESCRIPTION
**Pull request by kazzarin**
Fixes https://kitsu.canny.io/bugs/p/multi-window-problems-1

Changes proposed in this pull request:

- ~~Removed the fixed height on episode images~~
- Changed the grid layout of episodes

/cc @hummingbird-me/staff

### CODE REVIEW

**Comment by trmcnvn** [comment]
I feel like this would introduce other issues with different sized images, no? 

/cc @wopian @JoshFabian

**Comment by kazzarin** [comment]
I suppose it could, though I haven't seen any images yet that have a different aspect ratio from the rest.

**Comment by NuckChorris** [comment]
The server should guarantee they're all the same size

**Comment by trmcnvn** [comment]
Are you sure? We don't apply styles to episodes so it's referencing the original file.

**Comment by NuckChorris** [comment]
Ah crap you're right in that case.  We should probably generate styles 🤔

**Comment by wopian** [comment]
This is better off fixed by changing the `col-sm-2` to `col-sm-6` and adding `object-fit: cover` to that `img` css

Before

After


Before

After

**Review by wopian — CHANGES_REQUESTED** [review]
This is better off fixed by changing the `col-sm-2` to `col-sm-6` and adding `object-fit: cover` to that `img` CSS to never have the image squished instead of removing its height

If the squares should be rectangular too, replace `col-md-4` with `col-lg-4`

Before

After


Before

After


Because right now this change will make them look like this:

**Review by wopian — APPROVED** [review]

**Pull request merged**
