### PR TITLE
Remove ugly padding on modals

### PR DESCRIPTION
**Pull request by sachaw**
Does not seem to match theme.

### CODE REVIEW

**Comment by wopian** [comment]
Simply deleting that has several side affects.

Delete modal

becomes


Report modal

becomes


However it does improve the profile edit modal, although it removes the top padding of the header

**Comment by JoshFabian** [comment]
This negatively effects too many existing modals.

**Review by wopian — CHANGES_REQUESTED** [review]
Simply deleting that has several side affects which aren't accounted for.

Delete modal

becomes


Report modal

becomes


However it does improve the profile edit modal, although it removes the top padding of the header

**Comment by sachaw** [comment]
Yea, sorry didn't test it, this was to specifically fix the modal that shows more activity in the feed for an item, so removing the padding for that specific modal will have the desired result.

**Pull request closed without merging**
