### PR TITLE
More profile links

### PR DESCRIPTION
**Pull request by matthewdias**
Changes proposed in this pull request:

add strings and svgs for profile links for:

- deviantart
- dribbble
- imdb
- last.fm
- letterboxd
- medium
- player.me
- reddit
- trakt

@josh these look okay to you?

### CODE REVIEW

**Comment by JoshFabian** [comment]
Looks good to me!

**Comment by trmcnvn** [comment]
Are you planning a PR to the server?

**Comment by matthewdias** [comment]
yep

**Comment by matthewdias** [comment]
https://github.com/hummingbird-me/hummingbird-server/pull/78 is ready for @NuckChorris

**Pull request merged**
