### PR TITLE
Improved library sorting

### PR DESCRIPTION
**Pull request by matthewdias**

### CODE REVIEW

**Review by trmcnvn — APPROVED** [review]

**Comment by matthewdias** [comment]
need to add a progress sort too.

**Comment by trmcnvn** [comment]
@JoshFabian Can you confirm you're happy with the small design change here?

**Comment by JoshFabian** [comment]
@matthewdias image broken

**Comment by matthewdias** [comment]
@JoshFabian nya.is ☠️  😞

**Pull request merged**
