### PR TITLE
Don't escape backslashes in posts/comments

### PR DESCRIPTION
**Pull request by cybrox**
Added this as a PR since it's a pretty hacky solution.
It can be merged in when needed but feel free to fix this in a cleaner way!

### CODE REVIEW

**Comment by trmcnvn** [comment]
Would be a better approach to use the [sanitizeInput](https://github.com/DockYard/ember-one-way-controls/blob/master/docs/one-way-input.md#sanitizing-the-input) function.

Since comments & posts use `expanding-textarea` you could just override it there.

**Comment by NuckChorris** [comment]
Isn't this because of the Markdown parser?

**Comment by trmcnvn** [comment]
Yep

**Comment by cybrox** [comment]
@vevix Knew there had to be a cleaner way... obviously. Thanks for pointing out.

**Comment by NuckChorris** [comment]
Wouldn't this make it impossible to escape Markdown characters like * and _?

**Comment by cybrox** [comment]
I guess replacing `/\[^_*#![(]/` would work.

**Comment by cybrox** [comment]
To roll this discussion up again, using `sanitizeInput` or the `update` method of `ember-one-way` components might be a bit of a semi-optimal solution for this, since those are reprocessed every time the value changes.

I think the cleanest solution would be to add a helper that does the modification and inejct it in the places this PR originally anchored on.

cc @vevix

**Comment by trmcnvn** [comment]
:+1: I think a utility makes more sense than a helper as we don't have any intention of calling this from a template.

**Pull request closed without merging**
