### PR TITLE
Remove colons from the status info in media page

### PR DESCRIPTION
**Pull request by Uricorn**

### CODE REVIEW

**Review by matthewdias — APPROVED** [review]

**Review by toyhammered — APPROVED** [review]
ayyyyyy!

**Review by wopian — DISMISSED** [review]
Too many colons

**Comment by NuckChorris** [comment]
I mean, it seems like a colonectomy would make more sense since we only used a colon in one place? 🤔

**Comment by matthewdias** [comment]
Yeah I guess. Original design didn't have em.

**Review by wopian — APPROVED** [review]

**Pull request merged**
