### PR TITLE
select number inputs on click

### PR DESCRIPTION
**Pull request by matthewdias**
is my naming okay here?

### CODE REVIEW

**Review by trmcnvn — CHANGES_REQUESTED** [review]
How does this affect clicking the arrow buttons within the input? Does it still select the text?

------

Can you move the component file to a new folder `components/ui/...` and invoke as `{{ui/selectable-input ...}}` as that is where I'm moving UI components going forward.

**Comment by matthewdias** [comment]
hmm, yeah that's an issue. apparently there's no way to detect that 🤔

**Comment by JoshFabian** [comment]
Still probably a better experience than users currently have. LGTM!

**Review by trmcnvn — APPROVED** [review]

**Pull request merged**
