### PR TITLE
Quick Update Flex - Safari

### PR DESCRIPTION
**Pull request by chrislegault**
- updated the styles so they work in safari

### CODE REVIEW

**Comment by trmcnvn** [comment]
The button is now properly aligned in Safari, Firefox, & Chrome! However, the button is incorrect when in its "Complete" state.

Example:

**Comment by chrislegault** [comment]
Alrighty, I'll fix that tonight

**Comment by chrislegault** [comment]
@vevix give it a go again

**Comment by trmcnvn** [comment]
Yep! :+1: awesome work.

**Pull request merged**
