### PR TITLE
Add Spanish translation

### PR DESCRIPTION
**Pull request by RAVMN**
Changes proposed in this pull request:
First draft of spanish translation.
¿Is there a staging server to test it?

/cc @hummingbird-me/staff

### CODE REVIEW

**Comment by wopian** [comment]
>¿Is there a staging server to test it?

You can run `yarn start` to get a local version of the client running on http://localhost:4200.

**Comment by RAVMN** [comment]
Got the local version running, have to change a couple of strings (like "Próximos animes populares") because it doesn't sound good.

@Zeroicedragon will help me proofreading

**Comment by wopian** [comment]
You can use `"` within YAML strings by escaping the character like `\"`

**Review by wopian — APPROVED** [review]

**Comment by wopian** [comment]
Ready for merge if translation is completed 👍

**Comment by RAVMN** [comment]
Hi @wopian , it is ready :D

**Pull request merged**
